spring:
  batch:
    job:
      enabled: false
  profiles:
    group:
      local:
        - data-local
        - cloud-local
      dev:
        - data-dev
        - cloud-dev
      prod:
        - data-prod
        - cloud-prod
  datasource:
    hikari:
      pool-name: batch-db-pool

  jackson:
    time-zone: Asia/Seoul
