spring:
  cloud:
    aws:
      region: ap-northeast-2
      stack.auto: false
      rekognition:
        credentials:
          accessKey: ${accessKey}
          secretKey: ${secretKey}
      s3:
        img:
          bucket: sooum-img
        fcm:
          bucket: sooum-fcm
          sdk: ${FCM_SDK}
        credentials:
          accessKey: ${accessKey}
          secretKey: ${secretKey}
        default-card-img: test/card/default/
        user-card-img: test/card/user/
        profile-img: test/profile/

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}